apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: acmeservices.acme.dev
spec:
  group: acme.dev
  names:
    plural: acmeservices
    singular: acmeservice
    kind: AcmeService
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              team:
                type: string
              replicas:
                type: integer
              imageName:
                type: integer
              imageVersion:
                type: integer
              headless:
                type: boolean
              port:
                type: integer
              resources:
                type: object
                properties:
                  limits:
                    type: object
                    additionalProperties:
                      type: string
                  requests:
                    type: object
                    additionalProperties:
                      type: string
              credentialsSecret:
                type: object
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
              labels:
                type: object
                additionalProperties:
                  type: string
              config:
                type: object
                additionalProperties:
                  type: string
              environment:
                type: object
                additionalProperties:
                  type: string
          status:
            type: object
            properties:
              secrets:
                type: array
                items:
                  type: string
              configMap:
                type: string
              deployment:
                type: string
              service:
                type: string
              ingress:
                type: string
