apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.valorl.dev
spec:
  group: acme.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                exampleTitle:
                  type: string
                exampleText:
                  type: string
            status:
              type: object
              properties:
                hasTitle:
                  type: boolean
                hasText:
                  type: boolean
  scope: Namespaced
  names:
    plural: examples
    singular: example
    kind: Example
    shortNames:
      - eg
